### ISSUE TITLE
Undefined 'value' on script run

### ISSUE THREAD

**Issue by Jacobknew** [dasilva333/dedupe-armor#1]
Forgive me if I am missing something obvious, I am fairly ignorant about node.js development. I am getting the following when I attempt to follow the instructions
```
dedupe-armor jknew$ node index.js
/Users/jknew/dev/dedupe-armor/index.js:128
            }).value;
              ^

TypeError: Cannot read property 'value' of undefined
    at /Users/jknew/dev/dedupe-armor/index.js:128:15
    at arrayEach (/Users/jknew/dev/dedupe-armor/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/jknew/dev/dedupe-armor/node_modules/lodash/lodash.js:9344:14)
    at /Users/jknew/dev/dedupe-armor/index.js:125:11
    at arrayEach (/Users/jknew/dev/dedupe-armor/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/jknew/dev/dedupe-armor/node_modules/lodash/lodash.js:9344:14)
    at /Users/jknew/dev/dedupe-armor/index.js:110:7
    at arrayEach (/Users/jknew/dev/dedupe-armor/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/jknew/dev/dedupe-armor/node_modules/lodash/lodash.js:9344:14)
    at Object.<anonymous> (/Users/jknew/dev/dedupe-armor/index.js:108:3)
dedupe-armor jknew$ ls
README.txt		create_report.bat	dimFivePaShim.js	dimStorageShim.js	junkPerkFilter.js	node_modules		package.json		report-v2.txt
config.js		destinyArmor.csv	dimFourPaShim.js	index.js		junkperks.ts		package-lock.json	report-json.txt		thoughts.txt
dedupe-armor jknew$
```

**Comment by Jacobknew** [comment]
Here is my destinyArmor.csv file for reference, in case you have a chance to look at this at all. Thanks for this tool, if I can get it working it will be an incredible lifesaver for me! As you can see from that file, my vault is... out of control...
[destinyArmor.csv.zip](https://github.com/dasilva333/dedupe-armor/files/3195429/destinyArmor.csv.zip)
